# Generated by Django 5.2.4 on 2025-08-07 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_agent_role'),
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='device_id',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='sensor_type',
            field=models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('gas', 'Gas Leak'), ('panic_button', 'Panic Button'), ('motion', 'Motion Sensor'), ('camera', 'Camera Feed')], default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='value',
            field=models.TextField(),
        ),
    ]
