# Generated by Django 5.2.4 on 2025-08-07 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_remove_agent_created_at_remove_agent_role_and_more'),
        ('alerts', '0003_remove_alert_agent_remove_alert_level_and_more'),
        ('iot', '0002_remove_sensordata_data_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('air', 'Air Quality Sensor'), ('traffic', 'Traffic Sensor'), ('infra', 'Infrastructure Sensor'), ('water', 'Water Sensor'), ('gas', 'Gas Leak Detector'), ('panic_button', 'Panic Button'), ('camera', 'Camera Feed'), ('motion', 'Motion Sensor')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.TextField(help_text='Can hold string, float, or JSON')),
                ('is_action_taken', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='iot.iotdevice')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
            ],
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
