# Generated by Django 5.2.4 on 2025-08-07 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('busy', 'Busy')], max_length=20)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
