# Generated by Django 5.2.4 on 2025-08-07 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='last_active',
        ),
        migrations.AddField(
            model_name='agent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 7, 4, 45, 52, 176840)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('alert_handler', 'Alert Handler'), ('report_generator', 'Report Generator'), ('sensor_monitor', 'Sensor Monitor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('active', 'Active'), ('error', 'Error')], default='idle', max_length=20),
        ),
    ]
