# Generated by Django 5.2.4 on 2025-08-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_remove_agent_description_alter_agent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('coordinator', 'Coordinator Agent'), ('environmental', 'Environmental Agent'), ('security', 'Security Agent')], max_length=50),
        ),
    ]
