# Generated by Django 5.2.4 on 2025-08-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_agent_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='role',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='status',
        ),
        migrations.AddField(
            model_name='agent',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('development', 'Development'), ('environment', 'Environment'), ('social', 'Social Cohesion'), ('sme', 'SME Support'), ('safety', 'Safety')], default='development', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='description',
            field=models.TextField(default='No description provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
