# Generated by Django 5.2.4 on 2025-08-07 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_agent_role'),
        ('alerts', '0001_initial'),
        ('iot', '0002_remove_sensordata_data_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='sent_to',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='method',
        ),
        migrations.AddField(
            model_name='alert',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent'),
        ),
        migrations.AddField(
            model_name='alert',
            name='level',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='triggered_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iot.sensordata'),
            preserve_default=False,
        ),
    ]
