# Generated by Django 5.2.4 on 2025-08-07 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_rename_sent_at_alert_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='level',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='title',
        ),
        migrations.AddField(
            model_name='alert',
            name='category',
            field=models.CharField(choices=[('environment', 'Environment'), ('security', 'Security'), ('infrastructure', 'Infrastructure'), ('social', 'Social')], default='general', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert',
            name='triggered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
