# Generated by Django 5.2.4 on 2025-08-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='reports/images/'),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='report',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/video/'),
        ),
        migrations.AddField(
            model_name='report',
            name='voice_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/voice/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('environment', 'Environmental'), ('security', 'Security'), ('maintenance', 'Maintenance'), ('other', 'Other'), ('urban', 'Urban Development'), ('sme', 'SME Support'), ('social', 'Social Cohesion')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
