# Generated by Django 4.2.13 on 2025-08-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='issue_proofs/'),
        ),
    ]
