# Generated by Django 4.2.13 on 2025-08-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='place_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
